#!/bin/bash
.  _sql

if [[ $1 ]]
then
	where=" WHERE USER_NAME='$1'"
fi

_sql_statement="

$sql_wide
--
SET FEEDBACK OFF
SELECT 'DBA_STMT_AUDIT_OPTS' AS TABLE_NAME FROM DUAL;
SET FEEDBACK ON
SELECT * FROM DBA_STMT_AUDIT_OPTS $where order by AUDIT_OPTION;

SET FEEDBACK OFF
SELECT 'DBA_PRIV_AUDIT_OPTS' AS TABLE_NAME FROM DUAL;
SET FEEDBACK ON
SELECT * FROM DBA_PRIV_AUDIT_OPTS $where  order by PRIVILEGE;

SET FEEDBACK OFF
SELECT 'DBA_OBJ_AUDIT_OPTS' AS TABLE_NAME FROM DUAL;
SET FEEDBACK ON
SELECT * FROM DBA_OBJ_AUDIT_OPTS;
	
"

echo "$_sql_statement" 1>&2
echo "---------------------------------------------------------" 1>&2

sql "$_sql_statement"

# all these tables end up in sys.audit$
