#!/bin/bash
.  _sql

if [[ -z $1 ]]
then
	echo "Usage:db-audit-off <user-name>" 1>&2
	exit 1
fi

_sql_cmd="
	-- PRIVILEGES -- 
	NOAUDIT ALL PRIVILEGES BY $1 ;
	-- this seems not to work TODO: study
	NOAUDIT ALL BY $1 ;
	-- so we go by explicit naming
	NOAUDIT INSERT TABLE, UPDATE TABLE, DELETE TABLE, SELECT TABLE BY $1 ;
	NOAUDIT INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE, SELECT ANY TABLE BY $1;
	NOAUDIT EXECUTE ANY PROCEDURE BY $1;
	NOAUDIT EXECUTE PROCEDURE BY $1;
	
	
	
"
echo "$_sql_cmd" 1>&2
echo "---------------------------------------------------------" 1>&2

sql "$_sql_cmd"