#!/bin/bash
.  _sql


SESSIONID=$(cut -d"." -f1 <<< $1)
ENTRYID=$(cut -d"." -f2 <<< $1)

COLUMNS=${2:-'SQLBIND,SQLTEXT'}

#TODO: nice formatting

_sql_statement="
	
	$sql_porcelain
	$sql_wide
	SET LONG 9999
	SET LONGCHUNKSIZE 9999
	
	SELECT SQLBIND FROM sys.aud$ T WHERE SESSIONID=$SESSIONID  AND ENTRYID=$ENTRYID; 	
	SELECT SQLTEXT FROM sys.aud$ T WHERE SESSIONID=$SESSIONID  AND ENTRYID=$ENTRYID; 
	
	-- just checking, but returns the same
	-- SELECT SQL_BIND FROM DBA_AUDIT_TRAIL T WHERE SESSIONID=$SESSIONID  AND ENTRYID=$ENTRYID; 
	-- SELECT SQL_TEXT FROM DBA_AUDIT_TRAIL T WHERE SESSIONID=$SESSIONID  AND ENTRYID=$ENTRYID; 		

"
echo "$_sql_statement" 1>&2
echo "---------------------------------------------------------" 1>&2

data=$(sql "$_sql_statement")

echo "$data"

# draft of formating TODO: standalone formaters but probably outside of the init
#echo "$data" | sed -n "2p" | perl -pe "s;(#);\n\1;g" 
#echo "$data" | sed -n "4p" | perl -pe "s;INSERT INTO UNIUS.CPR_V_PARTNER \((.*)?\) VALUES \((.*)?\);\1\n\2;g" | perl -pe "s;(, :B[0-9]+);\1\n;g"



